backend:
  name: github
  repo: AssylEr/MedEr
  branch: main
  auth_type: pkce
  app_id: Ov23liFyiCUJ3SM2f6y5
  site_url: https://assyler.github.io/MedEr/

publish_mode: simple

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages & Content"
    files:
      - name: "home"
        label: "Home Page"
        file: "home.json"
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "text" }
          - label: "Arabic Content"
            name: "ar"
            widget: "object"
            fields:
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "text" }
      - name: "about"
        label: "About Us Page"
        file: "about.json"
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - { label: "Page Title", name: "page_title", widget: "string" }
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
              - { label: "Admin Section Title", name: "admin_title", widget: "string" }
              - { label: "Admin Section Description", name: "admin_desc", widget: "text" }
              - { label: "Contact Section Title", name: "contact_title", widget: "string" }
              - { label: "Contact Admin Line", name: "contact_admin", widget: "string" }
              - { label: "Contact Email Line", name: "contact_email", widget: "string" }
          - label: "Arabic Content"
            name: "ar"
            widget: "object"
            fields:
              - { label: "Page Title", name: "page_title", widget: "string" }
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
              - { label: "Admin Section Title", name: "admin_title", widget: "string" }
              - { label: "Admin Section Description", name: "admin_desc", widget: "text" }
              - { label: "Contact Section Title", name: "contact_title", widget: "string" }
              - { label: "Contact Admin Line", name: "contact_admin", widget: "string" }
              - { label: "Contact Email Line", name: "contact_email", widget: "string" }
      - name: "privacy"
        label: "Website Privacy Page"
        file: "privacy.json"
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - { label: "Page Title", name: "page_title", widget: "string" }
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
              - { label: "Introduction Title", name: "intro_title", widget: "string" }
              - { label: "Introduction Content", name: "intro_p1", widget: "text" }
              - { label: "Data Collection Title", name: "data_collection_title", widget: "string" }
              - { label: "Data Collection Content", name: "data_collection_p1", widget: "text" }
              - { label: "Types of Data Title", name: "data_type_title", widget: "string" }
              - { label: "Types of Data List (Markdown)", name: "data_type_list", widget: "markdown" }
              - { label: "Personal Info Title", name: "data_personal_title", widget: "string" }
              - { label: "Personal Info Content", name: "data_personal_p1", widget: "text" }
              - { label: "How We Use Title", name: "data_use_title", widget: "string" }
              - { label: "How We Use Content", name: "data_use_p1", widget: "text" }
              - { label: "How We Use List (Markdown)", name: "data_use_list", widget: "markdown" }
              - { label: "Sharing Title", name: "data_sharing_title", widget: "string" }
              - { label: "Sharing Content", name: "data_sharing_p1", widget: "text" }
              - { label: "Links Title", name: "links_title", widget: "string" }
              - { label: "Links Content", name: "links_p1", widget: "text" }
              - { label: "Security Title", name: "security_title", widget: "string" }
              - { label: "Security Content", name: "security_p1", widget: "text" }
              - { label: "Contact Title", name: "contact_title", widget: "string" }
              - { label: "Contact Content", name: "contact_p1", widget: "string" }
          - label: "Arabic Content"
            name: "ar"
            widget: "object"
            fields:
              - { label: "Page Title", name: "page_title", widget: "string" }
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
              - { label: "Introduction Title", name: "intro_title", widget: "string" }
              - { label: "Introduction Content", name: "intro_p1", widget: "text" }
              - { label: "Data Collection Title", name: "data_collection_title", widget: "string" }
              - { label: "Data Collection Content", name: "data_collection_p1", widget: "text" }
              - { label: "Types of Data Title", name: "data_type_title", widget: "string" }
              - { label: "Types of Data List (Markdown)", name: "data_type_list", widget: "markdown" }
              - { label: "Personal Info Title", name: "data_personal_title", widget: "string" }
              - { label: "Personal Info Content", name: "data_personal_p1", widget: "text" }
              - { label: "How We Use Title", name: "data_use_title", widget: "string" }
              - { label: "How We Use Content", name: "data_use_p1", widget: "text" }
              - { label: "How We Use List (Markdown)", name: "data_use_list", widget: "markdown" }
              - { label: "Sharing Title", name: "data_sharing_title", widget: "string" }
              - { label: "Sharing Content", name: "data_sharing_p1", widget: "text" }
              - { label: "Links Title", name: "links_title", widget: "string" }
              - { label: "Links Content", name: "links_p1", widget: "text" }
              - { label: "Security Title", name: "security_title", widget: "string" }
              - { label: "Security Content", name: "security_p1", widget: "text" }
              - { label: "Contact Title", name: "contact_title", widget: "string" }
              - { label: "Contact Content", name: "contact_p1", widget: "string" }
      - name: "apps"
        label: "Applications"
        file: "apps.json"
        editor:
          preview: false
        fields:
          - name: "applications"
            label: "Applications"
            label_singular: "Application"
            widget: "list"
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Is Placeholder", name: "is_placeholder", widget: "boolean", default: false }
              - { label: "App Page Link", name: "href", widget: "string" }
              - { label: "Thumbnail Image", name: "imgSrc", widget: "image" }
              - { label: "Image Alt Text", name: "alt", widget: "string" }
              - label: "English Content"
                name: "en"
                widget: "object"
                fields:
                  - { label: "App Name", name: "name", widget: "string" }
                  - { label: "Short Description", name: "short_desc", widget: "text" }
                  - { label: "Page Title", name: "page_title", widget: "string" }
                  - { label: "Header Title", name: "header_title", widget: "string" }
                  - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
                  - { label: "Intro Section Title", name: "intro_title", widget: "string" }
                  - { label: "Intro Section Description", name: "intro_desc", widget: "markdown" }
                  - { label: "Features Section Title", name: "features_title", widget: "string" }
                  - { label: "Features Section Description", name: "features_desc", widget: "markdown" }
                  - { label: "Features List", name: "features_list", widget: "list", field: { label: "Feature Item (HTML allowed)", name: "item", widget: "string" } }
                  - { label: "Gallery Section Title", name: "gallery_title", widget: "string" }
                  - { label: "Gallery Section Description", name: "gallery_desc", widget: "markdown" }
                  - { label: "How-To Section Title", name: "howto_title", widget: "string" }
                  - { label: "How-To Section Description", name: "howto_desc", widget: "markdown" }
                  - { label: "How-To Steps", name: "howto_steps", widget: "list", field: { label: "Step (HTML allowed)", name: "item", widget: "string" } }
                  - { label: "Privacy Section Title", name: "privacy_title", widget: "string" }
                  - { label: "Privacy Section Description", name: "privacy_desc", widget: "markdown" }
                  - { label: "Privacy Points", name: "privacy_points", widget: "list", field: { label: "Point (HTML allowed)", name: "item", widget: "string" } }
                  - { label: "Privacy Summary", name: "privacy_summary", widget: "string" }
                  - { label: "Privacy Button Text", name: "privacy_btn_text", widget: "string" }
                  - { label: "Footer Title", name: "footer_title", widget: "string" }
                  - { label: "Footer Description", name: "footer_desc", widget: "string" }
                  - { label: "Download Button Text", name: "download_btn_text", widget: "string" }
                  - { label: "Privacy Policy Page Title", name: "privacy_page_title", widget: "string" }
                  - { label: "Privacy Policy Header Title", name: "privacy_header_title", widget: "string" }
                  - { label: "Privacy Policy Header Subtitle", name: "privacy_header_subtitle", widget: "string" }
                  - { label: "Privacy Policy Content", name: "privacy_content", widget: "markdown" }
              - label: "Arabic Content"
                name: "ar"
                widget: "object"
                fields:
                  - { label: "App Name", name: "name", widget: "string" }
                  - { label: "Short Description", name: "short_desc", widget: "text" }
                  - { label: "Page Title", name: "page_title", widget: "string" }
                  - { label: "Header Title", name: "header_title", widget: "string" }
                  - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
                  - { label: "Intro Section Title", name: "intro_title", widget: "string" }
                  - { label: "Intro Section Description", name: "intro_desc", widget: "markdown" }
                  - { label: "Features Section Title", name: "features_title", widget: "string" }
                  - { label: "Features Section Description", name: "features_desc", widget: "markdown" }
                  - { label: "Features List", name: "features_list", widget: "list", field: { label: "Feature Item (HTML allowed)", name: "item", widget: "string" } }
                  - { label: "Gallery Section Title", name: "gallery_title", widget: "string" }
                  - { label: "Gallery Section Description", name: "gallery_desc", widget: "markdown" }
                  - { label: "How-To Section Title", name: "howto_title", widget: "string" }
                  - { label: "How-To Section Description", name: "howto_desc", widget: "markdown" }
                  - { label: "How-To Steps", name: "howto_steps", widget: "list", field: { label: "Step (HTML allowed)", name: "item", widget: "string" } }
                  - { label: "Privacy Section Title", name: "privacy_title", widget: "string" }
                  - { label: "Privacy Section Description", name: "privacy_desc", widget: "markdown" }
                  - { label: "Privacy Points", name: "privacy_points", widget: "list", field: { label: "Point (HTML allowed)", name: "item", widget: "string" } }
                  - { label: "Privacy Summary", name: "privacy_summary", widget: "string" }
                  - { label: "Privacy Button Text", name: "privacy_btn_text", widget: "string" }
                  - { label: "Footer Title", name: "footer_title", widget: "string" }
                  - { label: "Footer Description", name: "footer_desc", widget: "string" }
                  - { label: "Download Button Text", name: "download_btn_text", widget: "string" }
                  - { label: "Privacy Policy Page Title", name: "privacy_page_title", widget: "string" }
                  - { label: "Privacy Policy Header Title", name: "privacy_header_title", widget: "string" }
                  - { label: "Privacy Policy Header Subtitle", name: "privacy_header_subtitle", widget: "string" }
                  - { label: "Privacy Policy Content", name: "privacy_content", widget: "markdown" }
              - { label: "Screenshot Gallery Images", name: "screenshots", widget: "list", fields: [{ label: "Image", name: "src", widget: "image" }] }
              - { label: "Google Play Store Link", name: "play_store_link", widget: "string", required: false }