backend:
  name: github
  repo: AssylEr/MedEr # هام: استبدل هذا باسم المستخدم/المستودع الخاص بك على GitHub
  branch: main # أو الفرع الافتراضي للمستودع الخاص بك
  auth_type: implicit # This enables GitHub's implicit auth flow

media_folder: "uploads" # سيتم تخزين ملفات الوسائط في المستودع تحت مجلد uploads
public_folder: "/uploads" # مسار الصور عند عرضها في الموقع

collections:
  - name: "pages"
    label: "Pages & Content"
    files:
      - name: "home"
        label: "Home Page"
        file: "home.json"
        description: "تحرير المحتوى الرئيسي لصفحة 'الرئيسية'."
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - { label: "Header Title", name: "header_title", widget: "string", hint: "العنوان الكبير في أعلى الصفحة الرئيسية. يمكنك استخدام <span></span> لتلوين جزء من النص." }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "text" }
          - label: "Arabic Content"
            name: "ar"
            widget: "object"
            fields:
              - { label: "Header Title", name: "header_title", widget: "string", hint: "العنوان الكبير في أعلى الصفحة الرئيسية. يمكنك استخدام <span></span> لتلوين جزء من النص." }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "text" }
      - name: "about"
        label: "About Us Page"
        file: "about.json"
        description: "تحرير محتوى صفحة 'من نحن'."
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - { label: "Page Title", name: "page_title", widget: "string" }
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
              - { label: "Admin Section Title", name: "admin_title", widget: "string" }
              - { label: "Admin Section Description", name: "admin_desc", widget: "text" }
              - { label: "Contact Section Title", name: "contact_title", widget: "string" }
              - { label: "Contact Admin Line", name: "contact_admin", widget: "string", hint: "Example: 'Admin: The RuyaX Team'" }
              - { label: "Contact Email Line", name: "contact_email", widget: "string", hint: "Example: 'Email: contact@ruyax.dev'" }
          - label: "Arabic Content"
            name: "ar"
            widget: "object"
            fields:
              - { label: "Page Title", name: "page_title", widget: "string" }
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
              - { label: "Admin Section Title", name: "admin_title", widget: "string" }
              - { label: "Admin Section Description", name: "admin_desc", widget: "text" }
              - { label: "Contact Section Title", name: "contact_title", widget: "string" }
              - { label: "Contact Admin Line", name: "contact_admin", widget: "string", hint: "مثال: 'المسؤول: فريق RuyaX'" }
              - { label: "Contact Email Line", name: "contact_email", widget: "string", hint: "مثال: 'البريد الإلكتروني: contact@ruyax.dev'" }
      - name: "privacy"
        label: "Website Privacy Page"
        file: "privacy.json"
        description: "تحرير محتوى صفحة 'سياسة الخصوصية' الخاصة بالموقع."
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - { label: "Page Title", name: "page_title", widget: "string" }
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
              - { label: "Introduction Title", name: "intro_title", widget: "string" }
              - { label: "Introduction Content", name: "intro_p1", widget: "text" }
              - { label: "Data Collection Title", name: "data_collection_title", widget: "string" }
              - { label: "Data Collection Content", name: "data_collection_p1", widget: "text" }
              - { label: "Types of Data Title", name: "data_type_title", widget: "string" }
              - { label: "Types of Data List (HTML)", name: "data_type_list", widget: "markdown", hint: "Use markdown list format." }
              - { label: "Personal Info Title", name: "data_personal_title", widget: "string" }
              - { label: "Personal Info Content", name: "data_personal_p1", widget: "text" }
              - { label: "How We Use Title", name: "data_use_title", widget: "string" }
              - { label: "How We Use Content", name: "data_use_p1", widget: "text" }
              - { label: "How We Use List (HTML)", name: "data_use_list", widget: "markdown", hint: "Use markdown list format." }
              - { label: "Sharing Title", name: "data_sharing_title", widget: "string" }
              - { label: "Sharing Content", name: "data_sharing_p1", widget: "text" }
              - { label: "Links Title", name: "links_title", widget: "string" }
              - { label: "Links Content", name: "links_p1", widget: "text" }
              - { label: "Security Title", name: "security_title", widget: "string" }
              - { label: "Security Content", name: "security_p1", widget: "text" }
              - { label: "Contact Title", name: "contact_title", widget: "string" }
              - { label: "Contact Content", name: "contact_p1", widget: "string", hint: "Don't include the mailto link, just the text." }
          - label: "Arabic Content"
            name: "ar"
            widget: "object"
            fields:
              - { label: "Page Title", name: "page_title", widget: "string" }
              - { label: "Header Title", name: "header_title", widget: "string" }
              - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
              - { label: "Introduction Title", name: "intro_title", widget: "string" }
              - { label: "Introduction Content", name: "intro_p1", widget: "text" }
              - { label: "Data Collection Title", name: "data_collection_title", widget: "string" }
              - { label: "Data Collection Content", name: "data_collection_p1", widget: "text" }
              - { label: "Types of Data Title", name: "data_type_title", widget: "string" }
              - { label: "Types of Data List (HTML)", name: "data_type_list", widget: "markdown", hint: "استخدم تنسيق القائمة في ماركداون." }
              - { label: "Personal Info Title", name: "data_personal_title", widget: "string" }
              - { label: "Personal Info Content", name: "data_personal_p1", widget: "text" }
              - { label: "How We Use Title", name: "data_use_title", widget: "string" }
              - { label: "How We Use Content", name: "data_use_p1", widget: "text" }
              - { label: "How We Use List (HTML)", name: "data_use_list", widget: "markdown", hint: "استخدم تنسيق القائمة في ماركداون." }
              - { label: "Sharing Title", name: "data_sharing_title", widget: "string" }
              - { label: "Sharing Content", name: "data_sharing_p1", widget: "text" }
              - { label: "Links Title", name: "links_title", widget: "string" }
              - { label: "Links Content", name: "links_p1", widget: "text" }
              - { label: "Security Title", name: "security_title", widget: "string" }
              - { label: "Security Content", name: "security_p1", widget: "text" }
              - { label: "Contact Title", name: "contact_title", widget: "string" }
              - { label: "Contact Content", name: "contact_p1", widget: "string", hint: "النص فقط، بدون رابط mailto." }
      - name: "apps"
        label: "Applications"
        file: "apps.json"
        description: "إدارة جميع التطبيقات المعروضة على الموقع من هنا."
        editor:
          preview: false
        fields:
          - name: "applications"
            label: "Applications"
            label_singular: "Application"
            widget: "list"
            fields:
              - { label: "Slug", name: "slug", widget: "string", hint: "معرّف فريد للتطبيق، يستخدم في الرابط (مثال: 'ruyax'). يجب أن يكون بأحرف إنجليزية صغيرة وبدون مسافات." }
              - { label: "Is Placeholder", name: "is_placeholder", widget: "boolean", default: false, hint: "حدد هذا الخيار إذا كان التطبيق غير متاح بعد." }
              - { label: "App Page Link", name: "href", widget: "string", hint: "الرابط إلى صفحة التطبيق. يجب أن يكون 'app.html?slug=الـSLUG_الذي_أدخلته_أعلاه'." }
              - { label: "Thumbnail Image", name: "imgSrc", widget: "image", hint: "صورة لبطاقة الصفحة الرئيسية ونافذة 'التطبيقات'." }
              - { label: "Image Alt Text", name: "alt", widget: "string", hint: "نص وصفي لصورة العرض المصغرة." }
              - label: "English Content"
                name: "en"
                widget: "object"
                fields:
                  - { label: "App Name", name: "name", widget: "string" }
                  - { label: "Short Description", name: "short_desc", widget: "text", hint: "تظهر على بطاقة الصفحة الرئيسية." }
                  - { label: "Page Title", name: "page_title", widget: "string", hint: "العنوان الذي يظهر في علامة تبويب المتصفح." }
                  - { label: "Header Title", name: "header_title", widget: "string", hint: "العنوان الكبير في أعلى صفحة التطبيق." }
                  - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
                  - { label: "Intro Section Title", name: "intro_title", widget: "string" }
                  - { label: "Intro Section Description", name: "intro_desc", widget: "markdown" }
                  - { label: "Features Section Title", name: "features_title", widget: "string" }
                  - { label: "Features Section Description", name: "features_desc", widget: "markdown" }
                  - label: "Features List"
                    name: "features_list"
                    widget: "list"
                    field: { label: "Feature Item (HTML allowed)", name: "item", widget: "string" }
                  - { label: "Gallery Section Title", name: "gallery_title", widget: "string" }
                  - { label: "Gallery Section Description", name: "gallery_desc", widget: "markdown" }
                  - { label: "How-To Section Title", name: "howto_title", widget: "string" }
                  - { label: "How-To Section Description", name: "howto_desc", widget: "markdown" }
                  - label: "How-To Steps"
                    name: "howto_steps"
                    widget: "list"
                    field: { label: "Step (HTML allowed)", name: "item", widget: "string" }
                  - { label: "Privacy Section Title", name: "privacy_title", widget: "string" }
                  - { label: "Privacy Section Description", name: "privacy_desc", widget: "markdown" }
                  - label: "Privacy Points"
                    name: "privacy_points"
                    widget: "list"
                    field: { label: "Point (HTML allowed)", name: "item", widget: "string" }
                  - { label: "Privacy Summary", name: "privacy_summary", widget: "string" }
                  - { label: "Privacy Button Text", name: "privacy_btn_text", widget: "string" }
                  - { label: "Footer Title", name: "footer_title", widget: "string" }
                  - { label: "Footer Description", name: "footer_desc", widget: "string" }
                  - { label: "Download Button Text", name: "download_btn_text", widget: "string" }
                  - { label: "Privacy Policy Page Title", name: "privacy_page_title", widget: "string", hint: "The title for the app's privacy policy page browser tab." }
                  - { label: "Privacy Policy Header Title", name: "privacy_header_title", widget: "string", hint: "The main, large title on the privacy policy page." }
                  - { label: "Privacy Policy Header Subtitle", name: "privacy_header_subtitle", widget: "string" }
                  - { label: "Privacy Policy Content", name: "privacy_content", widget: "markdown", hint: "Write the full privacy policy content here using Markdown." }
              - label: "Arabic Content"
                name: "ar"
                widget: "object"
                fields:
                  - { label: "App Name", name: "name", widget: "string" }
                  - { label: "Short Description", name: "short_desc", widget: "text", hint: "تظهر على بطاقة الصفحة الرئيسية." }
                  - { label: "Page Title", name: "page_title", widget: "string" }
                  - { label: "Header Title", name: "header_title", widget: "string" }
                  - { label: "Header Subtitle", name: "header_subtitle", widget: "string" }
                  - { label: "Intro Section Title", name: "intro_title", widget: "string" }
                  - { label: "Intro Section Description", name: "intro_desc", widget: "markdown" }
                  - { label: "Features Section Title", name: "features_title", widget: "string" }
                  - { label: "Features Section Description", name: "features_desc", widget: "markdown" }
                  - label: "Features List"
                    name: "features_list"
                    widget: "list"
                    field: { label: "Feature Item (HTML allowed)", name: "item", widget: "string" }
                  - { label: "Gallery Section Title", name: "gallery_title", widget: "string" }
                  - { label: "Gallery Section Description", name: "gallery_desc", widget: "markdown" }
                  - { label: "How-To Section Title", name: "howto_title", widget: "string" }
                  - { label: "How-To Section Description", name: "howto_desc", widget: "markdown" }
                  - label: "How-To Steps"
                    name: "howto_steps"
                    widget: "list"
                    field: { label: "Step (HTML allowed)", name: "item", widget: "string" }
                  - { label: "Privacy Section Title", name: "privacy_title", widget: "string" }
                  - { label: "Privacy Section Description", name: "privacy_desc", widget: "markdown" }
                  - label: "Privacy Points"
                    name: "privacy_points"
                    widget: "list"
                    field: { label: "Point (HTML allowed)", name: "item", widget: "string" }
                  - { label: "Privacy Summary", name: "privacy_summary", widget: "string" }
                  - { label: "Privacy Button Text", name: "privacy_btn_text", widget: "string" }
                  - { label: "Footer Title", name: "footer_title", widget: "string" }
                  - { label: "Footer Description", name: "footer_desc", widget: "string" }
                  - { label: "Download Button Text", name: "download_btn_text", widget: "string" }
                  - { label: "Privacy Policy Page Title", name: "privacy_page_title", widget: "string", hint: "العنوان لعلامة تبويب المتصفح لصفحة سياسة خصوصية التطبيق." }
                  - { label: "Privacy Policy Header Title", name: "privacy_header_title", widget: "string", hint: "العنوان الرئيسي الكبير في صفحة سياسة الخصوصية." }
                  - { label: "Privacy Policy Header Subtitle", name: "privacy_header_subtitle", widget: "string" }
                  - { label: "Privacy Policy Content", name: "privacy_content", widget: "markdown", hint: "اكتب محتوى سياسة الخصوصية الكامل هنا باستخدام الماركداون." }
              - { label: "Screenshot Gallery Images", name: "screenshots", widget: "list", field: { label: "Image", name: "src", widget: "image" }, hint: "صور لمعرض الصور في صفحة التطبيق." }
              - { label: "Google Play Store Link", name: "play_store_link", widget: "string", required: false, hint: "الرابط الكامل لمتجر Google Play." }